# Travis CI script

language: c

compiler:
  - gcc

os:
- linux

env:
- BUILD_TYPE=default

sudo: false

script:
  - make clean
  - make coverage && make test && make run-test && make coverage-info

after_success:
  - bash <(curl -s https://codecov.io/bash)